[MPDX-8088] Create setup start page
CruGlobal/mpdx-react pull request #1004
Opened 2024-08-22 21:44 UTC by canac

## Description

* Created a setup start page at `/setup/start` that lets the user pick their language.
* A future PR will handle automatically detecting when the user needs to start the setup tour.
* Added environment variables to Amplify.

https://jira.cru.org/browse/MPDX-8088

## Checklist:

- [x] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [x] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [x] I have requested a review from another person on the project

2024-08-23 14:23 UTC, dr-bizz requested changes
The code looks great! It still needs work on the design as it looks a little off compared to the rest of the design on MPDX.

![Screenshot 2024-08-23 at 10 18 00 AM](https://github.com/user-attachments/assets/561153ae-cf2b-4763-87cc-06595d4e071c)

2024-08-26 14:53 UTC, canac commented on src/components/Links/Links.test.tsx
Sure thing, I moved the components into `Shared`.

2024-08-26 14:56 UTC, canac commented
> The code looks great! It still needs work on the design as it looks a little off compared to the rest of the design on MPDX.

@dr-bizz I don't disagree that there's room for improvement. Let me know if you have any specific suggestions.

@j2trumpet Do you have any ideas for improving the design? I could put it in a card and/or add a blue background, but I'm at a loss besides those ideas. The Angular version looks like the screenshot in [this ticket](https://jira.cru.org/browse/MPDX-8088).

2024-08-26 16:06 UTC, j2trumpet commented
Nothing jumps out at me as looking bad. Looking at the Jira ticket, it looks like this screen is all the content on the page rather than a modal appearing over other content. Are there other screens during the account/app setup process that this language screen could be styled like?

2024-08-26 16:16 UTC, canac commented
> Are there other screens during the account/app setup process that this language screen could be styled like?

@j2trumpet The connect organization screen looks similar (https://jira.cru.org/browse/MPDX-8089). I'll definitely make these two screens look similar.

2024-08-26 16:57 UTC, canac commented
@dr-bizz I made the setup content a Card on a blue background. Let me know what you think.

2024-08-27 12:33 UTC, dr-bizz requested changes
I like the changes you made, it's starting to look great. I still think there is some room for improvement.

What are your thoughts to making it like this:

![Screenshot 2024-08-27 at 8 27 57 AM](https://github.com/user-attachments/assets/94d2ff13-9610-40e4-b233-bc69389d19ec)

2024-08-27 14:00 UTC, canac commented
@dr-bizz Does your comment on the other PR list the styles you changed to get that screenshot? I see you also made the button full-width. Did you change anything else?

> Header text: font-size: 2.75rem
> Icon colour: primary
> Paragraph - max-width: 500px
> Card max-width: 580px

2024-08-27 18:53 UTC, dr-bizz commented
> @dr-bizz Does your comment on the other PR list the styles you changed to get that screenshot? I see you also made the button full-width. Did you change anything else?
> 
> > Header text: font-size: 2.75rem
> > Icon colour: primary
> > Paragraph - max-width: 500px
> > Card max-width: 580px

I also made all the input and paragraphs in line with one another. But I think that is it.

2024-08-28 12:12 UTC, dr-bizz approved these changes
Looks awesome! Great job

2024-08-28 16:03 UTC, canac commented
> Oh just thought on the start pages, is it worth changing the colout of the help icon to something other than blue so it's more visible? - just a thought

Good idea. We're switching to HelpJuice pretty soon (I was working on the PR yesterday), and the HelpJuice beacon color is more different from the MPDX background color, so I'll probably leave it as-is if that's OK. And if the contrast doesn't end up being good enough, I can after that.

<img width="720" alt="Screenshot 2024-08-28 at 11 02 45 AM" src="https://github.com/user-attachments/assets/edcea08c-ed5a-4cab-aea3-544b81731faa">

2024-08-28 18:57 UTC, merged