[No Jira] Fix Email Addresses - Contact Links Work
CruGlobal/mpdx-react pull request #1005
Opened 2024-08-23 01:53 UTC by caleballdrin

## Description

- Make contact links clickable
- Move formik error messages so they don't throw off the alignment
- Only allow adding a number if it is not falsey
- styling improvements

## Checklist:

- [ ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

2024-08-23 22:49 UTC, caleballdrin commented
Codecov patch isn't passing but I don't think it is possible to get it to pass if you look at the 2 lines that are untested.

2024-08-26 14:37 UTC, canac requested changes
> Codecov patch isn't passing but I don't think it is possible to get it to pass. There are just 2 lines that are untested.

I think a test like this will make it pass:

```tsx
  it('should show errors', async () => {
    const { findAllByRole, findByText } = render(<Components />);

    userEvent.clear((await findAllByRole('textbox'))[0]);
    expect(await findByText('This field is required')).toBeInTheDocument();
  });
```

Thanks for making the contacts panel open up!

2024-08-26 14:37 UTC, canac commented on src/components/Tool/FixPhoneNumbers/Contact.tsx
> +                                  title="Set as Primary"
Not your change, but can you localize this label?

2024-08-26 14:37 UTC, canac commented on src/components/Tool/FixPhoneNumbers/Contact.tsx
> +                              <Tooltip title="Delete Number" placement="left">
Can we localize this label too?

2024-08-26 14:37 UTC, canac commented on src/components/Tool/FixPhoneNumbers/Contact.tsx
> +                          values.people[personIndex].newPhoneNumber &&
Can we use an `if` block instead of `&&`?

2024-08-26 14:37 UTC, canac commented on pages/accountLists/[accountListId]/tools/fix/phoneNumbers/[[...contactId]].page.test.tsx
> +            mocks={GetInvalidPhoneNumbersMocks as ApolloErgonoMockMap}
This `as` can be removed.

2024-08-26 14:37 UTC, canac commented on pages/accountLists/[accountListId]/tools/fix/phoneNumbers/[[...contactId]].page.test.tsx
> +        `/accountLists/${accountListId}/tools/fix/phoneNumbers/${'testid'}`,
Or you can use the id from the mocks.

```suggestion
        `/accountLists/${accountListId}/tools/fix/phoneNumbers/testid`,
```

2024-09-03 20:50 UTC, canac approved these changes

2024-09-03 20:59 UTC, merged