Appeal list contact row functionality
CruGlobal/mpdx-react pull request #1013
Opened 2024-08-27 21:31 UTC by dr-bizz

## Description
In this PR, I added functionality to the contact row. Allow the user to add a pledge, edit a pledge, delete a pledge, remove a contact from an appeal and add an excluded contact.

You will see I added some files from the commit `[1. List Filters - Add contacts to appeal](https://github.com/CruGlobal/mpdx-react/commit/c2412ee8379da48151c5e0cdfc13e81d0862fd3c)` otherwise this PR would break.  This should be merged in before this merges so I will remove that once that happens.

## Checklist:

- [ ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

2024-08-27 21:47 UTC, dr-bizz commented
If `codecov/patch`  is above 80% I have been approving PRs as that is a pass in my book.

2024-08-27 22:04 UTC, canac requested changes
I haven't tested it thoroughly yet but here's my comments so far.

2024-08-27 22:15 UTC, dr-bizz commented
@canac I can't see you comments

2024-08-28 18:18 UTC, canac requested changes
Looking great! Just some minor suggestions.

2024-08-28 19:50 UTC, dr-bizz commented on src/components/Tool/Appeal/List/ContactRow/ContactRow.tsx
> +  date?: any;
Renamed to `dateOrFrequency`

2024-08-28 19:54 UTC, dr-bizz commented on src/components/Tool/Appeal/List/ContactRow/ContactRow.tsx
> +          donation?.appealAmount?.amount &&
I've made it simplier

2024-08-28 20:00 UTC, dr-bizz commented on src/components/Tool/Appeal/Modals/DeleteAppealContact/DeleteAppealContactModal.test.tsx
> +  let cardinality = 0;
For sure! Whatever makes it easier to understand

2024-08-28 20:03 UTC, dr-bizz commented on src/components/Tool/Appeal/Modals/DeletePledgeModal/DeletePledgeModal.tsx
> +    setMutating(true);
I love this feature, can't believe I know about it before

2024-08-28 20:16 UTC, dr-bizz commented on src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.tsx
> +                  disabled={true}
Great point!

2024-08-28 20:16 UTC, dr-bizz commented on src/components/Tool/Appeal/Modals/PledgeModal/PledgeModal.tsx
> +                            <MenuItem value={''} disabled></MenuItem>
Removed blank entry

2024-08-28 21:32 UTC, canac approved these changes

2024-08-28 21:32 UTC, canac commented on src/components/Tool/Appeal/List/ContactRow/ContactRow.tsx
> +        if (amount && currency) {
I didn't realize what you were trying to accomplish was so simple. I thought there was a branch where you needed to render the raw amount without calling currency format. Thanks for making the logic verbose and clear! If you wanted to simplify, you could do `const donationAmount = currencyFormat(amount && currency ? amount : 0, currency, locale);`

2024-08-29 12:28 UTC, merged