report items constant to reuse
CruGlobal/mpdx-react pull request #103
Opened 2021-06-16 03:21 UTC by hotcakedev628

2021-06-16 17:46 UTC, OzzieOrca requested changes
Ya this looks like a good strategy. Once you merge your other PR, feel free to refactor both menus to use this file.

Can you make it a `.ts` file too?

2021-06-16 17:46 UTC, OzzieOrca commented on src/components/Reports/ReportLayout/NavReportsList/ReportItems.js
> +export default [
```suggestion
export const ReportNavItems = [
```

2021-06-16 18:22 UTC, hotcakedev628 commented
@OzzieOrca Sure thing. But I just wondered if I could do it since the app didn't import any `.ts` files.

2021-06-16 18:27 UTC, OzzieOrca commented
It should work. There's some `.ts` files around.

2021-06-22 14:41 UTC, hotcakedev628 commented
@OzzieOrca Can I merge this one?

2021-06-22 17:34 UTC, OzzieOrca approved these changes

2021-06-22 17:34 UTC, OzzieOrca commented on src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx
> +                                      ? ' (' + reportItem.subTitle + ')'
```suggestion
                                      ? ` (${reportItem.subTitle})`
```

2021-06-22 17:36 UTC, OzzieOrca approved these changes

2021-06-23 21:09 UTC, OzzieOrca commented
Looks like you've got one failing test.

2021-06-24 18:27 UTC, OzzieOrca approved these changes

2021-06-24 18:27 UTC, merged