[MPDX-8393] Make the Helpjuice beacon dismissable
CruGlobal/mpdx-react pull request #1150
Opened 2024-10-23 15:54 UTC by canac

## Description

Make the Helpjuice beacon dismissable. There is a new Hide Beacon link in the beacon widget that dismisses the beacon. Once dismissed, the beacon peeks just barely out from the right side of the screen. Hovering over it causes it to slide out, and clicking on it makes it no longer dismissed.

On most pages, the dismissed preference is saved to a persistent user preference. On login and error pages, we don't have an Apollo client, so the preference can't be persisted, but the beacon can still be temporarily dismissed until the next page load.

I had to jump through some hoops to get this to work, but the complexity is abstracted away into the `Helpjuice` component, and the comments for `ApolloBeacon` and `NoApolloBeacon` should describe what is going on. I chose not to do something like this because although it might technically work, it violates React's rules of hooks that hooks must not be conditionally called.

```tsx
const hasApolloClient = !useContext(getApolloContext());
const [dismissed, setDismissed] = hasApolloClient
  ? useUserPreference({
      key: 'beacon_dismissed',
      defaultValue: false,
    })
  : useState(false);
  return <DismissableBeacon dismissed={dismissed} setDismissed={setDismissed} />;
```

[MPDX-8393](https://jira.cru.org/browse/MPDX-8393)

## Checklist:

- [x] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [x] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [x] I have requested a review from another person on the project

2024-10-23 18:50 UTC, dr-bizz requested changes
The code looks great, but when I test it on the preview link, the beacon is visible after a refresh

2024-10-23 19:21 UTC, canac commented
@dr-bizz Good catch! I messed up the `hasApolloCheck`.

2024-10-23 19:39 UTC, dr-bizz reviewed
One thought I had to improve the Help Jiuce beacon is when it is clicked, the icon changes to a close button, as it isn't obvious you have to click it again to close it, and some users might click on hide beacon thinking it will just close the beacon.

<img width="432" alt="Screenshot 2024-10-23 at 3 35 40 PM" src="https://github.com/user-attachments/assets/7a04a960-d845-40f7-985b-7f6eecc38151">

2024-10-24 17:28 UTC, dr-bizz approved these changes
This is awesome! Thank you for adding on the x icon when it's open! it adds a lot to the user experience.

2024-10-24 17:39 UTC, merged