[no-Jira] Replace uuid package with native crypto.randomUUID
CruGlobal/mpdx-react pull request #1202
Opened 2024-11-18 19:05 UTC by canac

## Description

Replace the `uuid` package with the native `crypto.randomUUID()` method.

## Checklist:

- [x] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [x] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

2024-11-19 17:42 UTC, canac commented
This will need to wait for node 20. In node 18 `crypto` isn't a global, it has to be imported.

2025-04-24 14:38 UTC, dr-bizz requested changes
Thank you for doing this! I love it when we can remove packages and replace them with native functionality.

Please can you also remove the package `@types/uuid`?

2025-04-24 14:58 UTC, canac commented
> Please can you also remove the package `@types/uuid`?

@dr-bizz Good catch, thanks!

2025-04-24 16:53 UTC, dr-bizz approved these changes

2025-04-24 17:06 UTC, merged