MPDX-7136-Contacts-Tasks-Mass-Selection-Hook
CruGlobal/mpdx-react pull request #243
Opened 2021-11-02 16:02 UTC by TheNoodleMoose

This PR is for the creation of the ```useMassSelection``` hook, as well as adding the UI for the mass actions buttons. Connecting everything to the actions buttons and mass actions endpoint will happen in a separate PR(once the endpoint is available). Based the logic on the comments @OzzieOrca left in the [jira ticket](https://jira.cru.org/browse/MPDX-7136). Some of the logic can probably be cleaned up, but I at least got it working the way it should! Comments and questions appreciated 🙂

2021-11-02 21:02 UTC, OzzieOrca requested changes
Looks like a really clean way to do this! I like that you got pretty much all the code to live inside the hook :)

2021-11-03 13:20 UTC, TheNoodleMoose commented on pages/accountLists/[accountListId]/contacts/[[...contactId]].page.tsx
>    };
Yeah, I agree. Will update!

2021-11-03 13:30 UTC, TheNoodleMoose commented on src/hooks/useMassSelection.ts
> +  return {
You know I had it returning those and then was like "Oh I don't need those at the moment, let me just remove them"  haha. I'll add them back.

2021-11-03 13:47 UTC, TheNoodleMoose commented on src/hooks/__tests__/useMassSelection.test.ts
> +  //#region ToggleSelectionById Tests
Ah I forgot I left this in when I first tested regions. Maybe a combination of both? The ```describe``` adds organization in the tests suite and ``` the ```region```s can provide organization in the IDE.

2021-11-03 13:55 UTC, TheNoodleMoose commented on src/hooks/useMassSelection.ts
> +        if (currentIndex !== -1) {
Yeah, I like that better. I'll switch to that.

2021-11-03 14:26 UTC, TheNoodleMoose commented on src/components/Shared/Header/ListHeader.tsx
> -            <PlaceholderActionsDropdown />
I renamed it from ```PlaceholderActionsDropdown``` to ```ActionsButton```.

2021-11-03 19:55 UTC, OzzieOrca commented on src/hooks/__tests__/useMassSelection.test.ts
> +  //#region ToggleSelectionById Tests
Sure :)

2021-11-03 19:59 UTC, OzzieOrca approved these changes
🎉

2021-11-03 20:00 UTC, merged