MPDX-6909
CruGlobal/mpdx-react pull request #93
Opened 2021-05-25 20:27 UTC by reldredge71

2021-05-26 12:26 UTC, reldredge71 commented on .gitignore
> +node_modules
Yeah I did run `npm`.  I want to only run `yarn`, but every now and then VSCode suddenly throws me errors for every imported library, saying "cannot find module".  Like it was fine yesterday but I'm getting the errors again this morning.  Running `npm install` solves the issue for some reason.

2021-05-26 13:35 UTC, TheNoodleMoose commented on .gitignore
> +node_modules
Weird, and ```yarn start``` works fine after? If so you could probably just delete the changes to ```.gitignore``` and the ```package-lock.json``` in this pr and next time that happens delete them before committing as well. It's always annoying when random errors like that happen.

2021-06-22 12:27 UTC, reldredge71 commented
@TheNoodleMoose @OzzieOrca Could I have you guys look over my implementation of GraphQL-Rest for Coaching Questions here?  I'm held back right now because I can't seem to get the right data out of `CoachingAnswerSets.questions.attributes`.  Attributes seems to be null or undefined.

https://developers.mpdx.org/api/v2/coaching/questions
https://developers.mpdx.org/api/v2/coaching/answer_sets

2021-06-22 18:02 UTC, OzzieOrca requested changes
Whats up with the REST API? You may need to create a answer set first before you're able to load from it. The existing code should help figure out what to do but I can help too.

2021-06-22 18:19 UTC, reldredge71 commented
@OzzieOrca Yes there is already an answer set for one of the accounts, and it fetches the answer set, but I keep getting errors that the datahandler can't find the properties it needs.  `Attributes` doesn't seem to exist. I can't get a good idea of what what it's actually giving me to work with.

2021-06-22 18:21 UTC, reldredge71 commented on pages/api/Schema/CoachingAnswerSets/coachingAnswerSets.graphql
> +type CoachingQuestion {
I had that at one point, it gave me different errors.  I think it started to be a circular reference, either that or I have to update the actual REST query to actually fetch those relationships.  Either way, REST is failing on me as it is, I can always add these later.

2021-06-22 18:23 UTC, reldredge71 commented on pages/api/Schema/CoachingAnswerSets/coachingAnswerSets.graphql
> +}
Yes, but it might be used when we get to displaying answers in the Reports page.  I can remove them for now if you want.

2021-06-22 18:24 UTC, reldredge71 commented on src/components/Dashboard/Coaching/CoachingQuestionsModal/CoachingQuestionResponseSection/CoachingQuestionResponseSection.tsx
> +  }, [questionIndex]);
I was having a lot of issues with this stuff, I set it aside until I can actually test it with actual data.

2021-07-19 14:09 UTC, closed without merging