MPDX-7878 Performance Enhancements and Codebase Simplification
CruGlobal/mpdx-react pull request #950
Opened 2024-06-06 12:55 UTC by dr-bizz

## Description
This pull request includes several significant improvements and optimizations to enhance the performance and maintainability of our application:

1. **Loading Fonts via Font-Face:** Implemented font loading through the font-face method for faster and more efficient font rendering.

2. **Condensing CSS into One File:** Consolidated multiple CSS files into a single file to reduce HTTP requests and improve load times.

3. **Simplifying the Codebase:** Refactored and simplified the codebase for better readability and maintainability.
Adding Skeletons to Contacts and Tasks: Introduced skeleton loaders for Contacts and Tasks to improve user experience during data loading.

4. **Removing Delay on Dashboard:** Eliminated unnecessary delays on the dashboard for a smoother and more immediate user experience.

## Checklist:

- [ ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

2024-06-06 20:12 UTC, wrandall22 commented
run lighthouse

2024-06-07 12:48 UTC, wrandall22 commented
Looks like `github.head_ref` can be inconsistent (see this [discussion](https://github.com/orgs/community/discussions/25773)). This seems to be causing the lighthouse action to fail. They recommend using `github.event.pull_request.head.ref`, maybe we can do something like `https://${{ github.head_ref || github.event.pull_request.head.ref }}` (not sure if that syntax works in GHA or not) to get around this.

2024-06-07 19:38 UTC, dr-bizz commented
run lighthouse

2024-06-07 20:28 UTC, caleballdrin commented
I think the skeletons look great and definitely help with the UX. I noticed that when you stop scrolling it flashes to the skeletons. I think it was doing that before this PR but flashing to blank instead of the skeletons.

https://github.com/CruGlobal/mpdx-react/assets/47907831/df7bd29c-a912-4835-b3f5-c60ac0d06b4d

2024-06-11 12:59 UTC, dr-bizz commented
> I think the skeletons look great and definitely help with the UX. I noticed that when you stop scrolling it flashes to the skeletons. I think it was doing that before this PR but flashing to blank instead of the skeletons.
> 
>  contacts.loading.flashing.mov

So with this, this is actually a feature, not a bug. when you scroll up, we load the tasks above, but there is a split second where the tasks aren't loaded in, so we show the skeletons. `src/components/InfiniteList/InfiniteList.tsx` - line 117
```
ScrollSeekPlaceholder: Skeleton ? Skeleton : SkeletonItem,
```

2024-06-12 14:35 UTC, caleballdrin commented
@dr-bizz this seems like a bug to me because it loads and all the data is on the screen, then it flashes the skeletons, then it shows the loaded data again. Are you sure it isn't re-rendering an additional time unnecessarily?

2024-06-14 16:51 UTC, caleballdrin requested changes

2025-07-17 21:14 UTC, dr-bizz commented
I'm closing this. It has some good amendments in it like the skeletons, but a lot of the code is out of date.

2025-07-17 21:14 UTC, closed without merging