Mpdx 7930 clean up styles
CruGlobal/mpdx-react pull request #952
Opened 2024-06-11 15:49 UTC by dr-bizz

## Description

Please explain a bullet-point summary of the changes.
List any PRs that this PR is dependent on and any Jira tickets that this PR is related to.

## Checklist:

- [ ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

2024-06-11 17:26 UTC, dr-bizz commented
@caleballdrin The codecov will come later. This is just styling.

2024-06-11 20:46 UTC, caleballdrin commented
@dr-bizz is the amplify preview working for you? It's not working for me.

2024-06-12 00:04 UTC, caleballdrin requested changes
Could you make the  Add + icon be aligned with the Lock icons and have the same circle hover effect?

2024-06-12 13:32 UTC, dr-bizz commented
@caleballdrin it's due to it building on the staging API. Can you test locally?

2024-06-12 13:35 UTC, dr-bizz commented on src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx
> +                      <Select
Add icon is going away is a later PR. so I won't fix it.

2024-06-12 17:10 UTC, caleballdrin requested changes

2024-06-12 17:17 UTC, dr-bizz commented on src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx
> +                      <Select
I've correct the select box change. I got confused and replied to your PR review message here instead.

2024-06-12 17:29 UTC, dr-bizz commented on src/components/Tool/FixMailingAddresses/Contact.tsx
> +                <Grid item xs={12} md={6} className={classes.paddingB2}>
Done.

2024-06-12 17:29 UTC, dr-bizz commented on src/components/Tool/FixMailingAddresses/Contact.tsx
> +                        <StarIcon className={classes.hoverHighlight} />
Good find

2024-06-12 19:23 UTC, caleballdrin commented
Could you make the MPDX Source label aligned with the other sources? And also align the sources with the address on small screen sizes.

2024-06-13 18:44 UTC, caleballdrin approved these changes
Looks great!

2024-06-13 18:46 UTC, merged