MPDX-7935 add mailing address
CruGlobal/mpdx-react pull request #955
Opened 2024-06-13 18:40 UTC by dr-bizz

## Description

Please explain a bullet-point summary of the changes.
List any PRs that this PR is dependent on and any Jira tickets that this PR is related to.

## Checklist:

- [ ] I have given my PR a title with the format "MPDX-(JIRA#) (summary sentence max 80 chars)"
- [ ] I have applied the appropriate labels. (_Add the label "On Staging" to get the branch automatically merged into staging._)
- [ ] I have requested a review from another person on the project

2024-06-14 00:05 UTC, caleballdrin commented
@dr-bizz The code looks good! Now that you have the add address button you can remove the "MPDX" text. Could you also align the button with the address boxes?
<img width="846" alt="Screenshot 2024-06-13 at 5 02 53 PM" src="https://github.com/CruGlobal/mpdx-react/assets/47907831/bd1a06fb-fe85-4019-89bd-fc2caba6cfa5">

2024-06-14 00:10 UTC, caleballdrin commented
I also noticed that Tnt Imported addresses have a lock next to them. They should show an edit pen icon because they are editable.

2024-06-14 14:37 UTC, dr-bizz commented
> I also noticed that Tnt Imported addresses have a lock next to them. They should show an edit pen icon because they are editable.

I don't think they should be editable, as they weren't before on the old MPDX. I think this is due to ensuring TNT is the only place people can update their info if it's imported from TNT. 
Only is the source is MPDX, can it be edited on MPDX.

2024-06-14 16:48 UTC, caleballdrin commented
> I don't think they should be editable, as they weren't before on the old MPDX. I think this is due to ensuring TNT is the only place people can update their info if it's imported from TNT. Only is the source is MPDX, can it be edited on MPDX.

@dr-bizz They are editable in the old MPDX, it just also incorrectly shows a lock. There is no automatic update from Tnt like there is for Google and Siebel. Tnt import is more similar to a csv import where it is a one-time upload of data and then users will want to be able to edit that data in MPDX rather than going back to the csv/tnt file to re-import.

2024-06-14 18:56 UTC, dr-bizz commented
> > I don't think they should be editable, as they weren't before on the old MPDX. I think this is due to ensuring TNT is the only place people can update their info if it's imported from TNT. Only is the source is MPDX, can it be edited on MPDX.
> 
> @dr-bizz Tnt addresses **are** editable in the old MPDX, it just also incorrectly shows a lock. There is no automatic update from Tnt like there is for Google and Siebel. Tnt import is more similar to a csv import where it is a one-time upload of data and then users will want to be able to edit that data in MPDX rather than going back to the csv/tnt file to re-import.

@caleballdrin Fixed

2024-06-14 19:31 UTC, caleballdrin commented
@dr-bizz I'm pretty sure Tnt is different than DataServer. If you look at Pedros account you can see my contact was imported from Tnt.

2024-06-14 20:56 UTC, caleballdrin approved these changes
Nice work!

2024-06-14 21:10 UTC, caleballdrin requested changes

2024-06-14 21:10 UTC, caleballdrin commented on src/components/Tool/FixMailingAddresses/Contact.tsx
> +                  <Typography display="inline">
@dr-bizz this should be removed altogether, not changed to appName. "MPDX" is still showing up across from the "Add Address" button.

2024-06-17 14:49 UTC, caleballdrin approved these changes

2024-06-17 14:52 UTC, merged